export const PATHS = {
  dashboard: "/dashboard",
  accounts: "/accounts",
  accountNew: "/accounts/new",
  accountDetail: (id: string) => `/accounts/${id}`,
  screens: "/screens",
  screenNew: "/screens/new",
  customerAccounts: "/customer-accounts",
  customerAccountNew: "/customer-accounts/new",
  orders: "/orders",
  orderNew: "/orders/new",
  orderDetail: (id: string) => `/orders/${id}`,
  customers: "/customers",
  customerNew: "/customers/new",
  customerDetail: (id: string) => `/customers/${id}`,
  providers: "/providers",
  providerNew: "/providers/new",
  providerDetail: (id: string) => `/providers/${id}`,
  emails: "/emails",
  emailNew: "/emails/new",
  cobros: "/cobros",
  pagos: "/pagos",
  login: "/login",
} as const
