import type { Provider } from "./providers"
import type { Platform } from "./platforms"
import type { EmailAccount } from "./emails"
import type { Account } from "@/modules/accounts/types"
import type { DashboardResumen, Inventario } from "./dashboard"
import type { Screen } from "@/modules/screens/types"
import type { Customer } from "./customers"
import type { CustomerAccount } from "./customerAccounts"
import type { Order } from "./orders"

export const mockProviders: Provider[] = [
  {
    id: 1,
    name: "Juan Pérez Streaming",
    contact: "Juan Pérez",
    phone: "+57 312 3456789",
    notes: "Proveedor principal de Netflix y Disney. Muy confiable.",
    observaciones: "Pagos siempre los 15 de cada mes.",
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Premium Accounts LATAM",
    contact: "Carlos Mendoza",
    phone: "+54 9 11 2345-6789",
    notes: "Cuentas de Amazon Prime y Max (HBO).",
    observaciones: "Soporte rápido vía Telegram.",
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Soporte Digital Express",
    contact: "Ana Rodríguez",
    phone: "+52 55 1234 5678",
    notes: "Proveedor de Spotify Premium y Crunchyroll.",
    observaciones: "Entregas en menos de 2 horas.",
    created_at: new Date().toISOString(),
  },
]

export const mockPlatforms: Platform[] = [
  { id: 1, name: "Netflix Premium" },
  { id: 2, name: "Amazon Prime Video" },
  { id: 3, name: "Disney+ Estándar" },
  { id: 4, name: "Max (HBO)" },
  { id: 5, name: "Spotify Family" },
  { id: 6, name: "Crunchyroll Mega Fan" },
]

export const mockEmails: EmailAccount[] = [
  {
    id: 1,
    email: "netflix.premium01@gmail.com",
    password: "Password123*",
    notes: "Correo verificado por SMS. Todo en orden.",
    provider: 1,
    provider_id: 1,
    is_active: true,
  },
  {
    id: 2,
    email: "disney.latam.family@hotmail.com",
    password: "DisneyPass987!",
    notes: "Requiere verificación de código ocasional.",
    provider: 1,
    provider_id: 1,
    is_active: true,
  },
  {
    id: 3,
    email: "carlos.mendoza.hbo@gmail.com",
    password: "CarlosHBOSecure",
    notes: "Pago anual por el proveedor Carlos.",
    provider: 2,
    provider_id: 2,
    is_active: true,
  },
  {
    id: 4,
    email: "music.spotify.lisa@gmail.com",
    password: "SpotifyPassword2026",
    notes: "Familia Spotify. Renovación mensual.",
    provider: 3,
    provider_id: 3,
    is_active: true,
  },
  {
    id: 5,
    email: "temp.expired.account@gmail.com",
    password: "ExpiredPassword",
    notes: "Cuenta que no se renovó el mes pasado.",
    provider: 2,
    provider_id: 2,
    is_active: false,
  },
]

export const mockAccounts: Account[] = [
  {
    id: 1,
    email: 1,
    platform: 1,
    platform_name: "Netflix Premium",
    email_address: "netflix.premium01@gmail.com",
    max_screens: 4,
    credentials: "Perfil 1: PIN 1234, Perfil 2: PIN 5678",
    status: "activo",
    purchase_price: 15.50,
    fecha_compra: "2026-05-15",
    fecha_pago: "2026-06-15",
    fecha_corte: "2026-06-15",
    observaciones: "Renovación automática.",
    notes: "Pantallas asignadas a clientes VIP.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    email: 2,
    platform: 3,
    platform_name: "Disney+ Estándar",
    email_address: "disney.latam.family@hotmail.com",
    max_screens: 2,
    credentials: "Sin PIN en los perfiles",
    status: "por_vencer",
    purchase_price: 8.99,
    fecha_compra: "2026-05-20",
    fecha_pago: "2026-06-20",
    fecha_corte: "2026-06-20",
    observaciones: "Recordar al proveedor pagar a tiempo.",
    notes: "Vence pronto.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    email: 3,
    platform: 4,
    platform_name: "Max (HBO)",
    email_address: "carlos.mendoza.hbo@gmail.com",
    max_screens: 3,
    credentials: "HBO_User_Pass",
    status: "caida",
    purchase_price: 12.00,
    fecha_compra: "2026-05-01",
    fecha_pago: "2026-06-01",
    fecha_corte: "2026-06-01",
    observaciones: "Se cayó la sesión. Proveedor está revisando.",
    notes: "Reportada por cliente hace 2 días.",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    email: 4,
    platform: 5,
    platform_name: "Spotify Family",
    email_address: "music.spotify.lisa@gmail.com",
    max_screens: 5,
    credentials: "lisa_spotify // pass",
    status: "vencida",
    purchase_price: 14.99,
    fecha_compra: "2026-04-10",
    fecha_pago: "2026-05-10",
    fecha_corte: "2026-05-10",
    observaciones: "Esperando confirmación de renovación.",
    notes: "Corte realizado.",
    is_active: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockDashboardResumen: DashboardResumen = {
  ingresos: {
    orders_total: 1500,
    screens_total: 120,
    customer_accounts_total: 45,
    total: 2500,
  },
  egresos: 850,
  balance: 1650,
  conteos: {
    cuentas_activas: 4,
    pantallas_vendidas: 14,
    pantallas_disponibles: 6,
    ordenes_activas: 28,
  },
}

export const mockInventario: Inventario = {
  cuentas: [
    { plataforma: "Netflix Premium", total: 2, disponibles: 1, activas: 1, por_vencer: 0, vencidas: 0, caidas: 0 },
    { plataforma: "Disney+ Estándar", total: 1, disponibles: 0, activas: 0, por_vencer: 1, vencidas: 0, caidas: 0 },
    { plataforma: "Max (HBO)", total: 1, disponibles: 0, activas: 0, por_vencer: 0, vencidas: 0, caidas: 1 },
  ],
  totales: {
    total: 4,
    disponibles: 1,
    activas: 1,
    por_vencer: 1,
    vencidas: 1,
    caidas: 1,
  },
}

export const mockCustomers: Customer[] = [
  {
    id: 1,
    name: "Leidisita Gómez",
    phone: "3154829910",
    notes: "Cliente recurrente de combos de streaming.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Nataly COPOWER",
    phone: "3209871122",
    notes: "Tiene pantallas adicionales activas.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Salome Esposo",
    phone: "3103445588",
    notes: "Paga adelantado.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Dairo Vargas",
    phone: "3004455667",
    notes: "Prefiere cuentas completas.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockScreens: Screen[] = [
  {
    id: 1,
    account: 1,
    account_info: "netflix.premium01@gmail.com (Netflix Premium)",
    customer: 1,
    customer_name: "Leidisita Gómez",
    order: 1,
    pin: "1212",
    precio_venta: 12000,
    profile_name: "Perfil Leidi",
    status: "activo",
    fecha_inicio: "2026-05-26",
    fecha_cobro: "2026-06-25",
    fecha_corte: "2026-06-26",
    observaciones: "Asignado en combo",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    account: 1,
    account_info: "netflix.premium01@gmail.com (Netflix Premium)",
    customer: 2,
    customer_name: "Nataly COPOWER",
    order: 2,
    pin: "6571",
    precio_venta: 12000,
    profile_name: "Perfil Nataly",
    status: "por_vencer",
    fecha_inicio: "2026-06-04",
    fecha_cobro: "2026-07-03",
    fecha_corte: "2026-07-04",
    observaciones: "Pago pendiente",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    account: 2,
    account_info: "disney.latam.family@hotmail.com (Disney+ Estándar)",
    status: "disponible",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export const mockCustomerAccounts: CustomerAccount[] = [
  {
    id: 1,
    account: 1,
    platform_name: "Netflix Premium",
    email_address: "netflix.premium01@gmail.com",
    customer: 3,
    customer_name: "Salome Esposo",
    order: 3,
    contrasena: "NetflixSalome99*",
    precio_venta: 35000,
    profile_name: "Familia Salome",
    status: "activo",
    fecha_inicio: "2026-05-18",
    fecha_cobro: "2026-06-17",
    fecha_corte: "2026-06-18",
    observaciones: "Cuenta completa vendida",
  },
  {
    id: 2,
    account: 3,
    platform_name: "Max (HBO)",
    email_address: "carlos.mendoza.hbo@gmail.com",
    customer: 4,
    customer_name: "Dairo Vargas",
    order: 4,
    contrasena: "MaxPassDairo",
    precio_venta: 30000,
    profile_name: "Casa Dairo",
    status: "caida",
    fecha_inicio: "2026-06-01",
    fecha_cobro: "2026-06-30",
    fecha_corte: "2026-07-01",
    observaciones: "Reportado por soporte",
  },
]

export const mockOrders: Order[] = [
  {
    id: 1,
    customer: 1,
    customer_name: "Leidisita Gómez",
    total: 37000,
    status: "activo",
    fecha_inicio: "2026-05-26",
    fecha_cobro: "2026-06-25",
    fecha_corte: "2026-06-26",
    observaciones: "Combo completo Leidi",
  },
  {
    id: 2,
    customer: 2,
    customer_name: "Nataly COPOWER",
    total: 34000,
    status: "por_vencer",
    fecha_inicio: "2026-06-04",
    fecha_cobro: "2026-07-03",
    fecha_corte: "2026-07-04",
    observaciones: "Cobrar a inicio de mes",
  },
  {
    id: 3,
    customer: 3,
    customer_name: "Salome Esposo",
    total: 27000,
    status: "vencida",
    fecha_inicio: "2026-05-18",
    fecha_cobro: "2026-06-17",
    fecha_corte: "2026-06-18",
    observaciones: "Pago demorado",
  },
]

